/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    countries: Country;
    reviews: Review;
    Subscripe: Subscripe;
    Notes: Note;
    'shipping-zones': ShippingZone;
    orders: Order;
    favorites: Favorite;
    'product-views': ProductView;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    Subscripe: SubscripeSelect<false> | SubscripeSelect<true>;
    Notes: NotesSelect<false> | NotesSelect<true>;
    'shipping-zones': ShippingZonesSelect<false> | ShippingZonesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'product-views': ProductViewsSelect<false> | ProductViewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    collections: Collection;
    'about-page': AboutPage;
    faqs: Faq;
    'contact-us-page': ContactUsPage;
    footer: Footer;
    'notes-page': NotesPage;
    policy: Policy;
    'shipping-delivery': ShippingDelivery;
    'terms-and-conditions': TermsAndCondition;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'contact-us-page': ContactUsPageSelect<false> | ContactUsPageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'notes-page': NotesPageSelect<false> | NotesPageSelect<true>;
    policy: PolicySelect<false> | PolicySelect<true>;
    'shipping-delivery': ShippingDeliverySelect<false> | ShippingDeliverySelect<true>;
    'terms-and-conditions': TermsAndConditionsSelect<false> | TermsAndConditionsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  gender: 'male' | 'female';
  pendingEmail?: string | null;
  pendingEmailToken?: string | null;
  pendingEmailTokenExpiresAt?: string | null;
  role: 'user' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  titleAr: string;
  des: string;
  desAr: string;
  slug: string;
  slugAr: string;
  showInHomePage?: boolean | null;
  ImageSource?: ('Url' | 'upload') | null;
  ImageUrl?: string | null;
  uploadImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  titleAr?: string | null;
  subtitle?: string | null;
  subtitleAr?: string | null;
  longDes?: string | null;
  longDesAr?: string | null;
  slug: string;
  slugAr: string;
  isNewest: boolean;
  ShowInDiscountSection: boolean;
  important?: boolean | null;
  isBestSeller?: boolean | null;
  category: string | Category;
  type?: string | null;
  typeAr?: string | null;
  choices: {
    choiceType: 'color' | 'quantity' | 'types' | 'size';
    choiceTypeAr: 'لون' | 'كمية' | 'نوع' | 'حجم';
    options?:
      | {
          value: string;
          valueAr: string;
          availability?: ('inStock' | 'outOfStock') | null;
          priceAfter: number;
          priceBefore: number;
          ImageSource?: ('Url' | 'upload') | null;
          image?: (string | null) | Media;
          imageUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  title: string;
  titleAr: string;
  reviewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  title: string;
  titleAr?: string | null;
  subtitle: string;
  subtitleAr?: string | null;
  des: string;
  desAr: string;
  country?: (string | null) | Country;
  rate?: number | null;
  ClientName?: (string | null) | User;
  isApproved?: boolean | null;
  product?: (string | null) | Product;
  productOption?: string | null;
  image?: {
    ImageSource?: ('upload' | 'Url') | null;
    image?: (string | null) | Media;
    imageUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Subscripe".
 */
export interface Subscripe {
  id: string;
  Email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Notes".
 */
export interface Note {
  id: string;
  title: string;
  titleAr: string;
  slug: string;
  slugAr: string;
  des: string;
  desAr: string;
  longDes: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  lonDesAr: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  brandName: string;
  brandNameAr: string;
  isImportant?: boolean | null;
  ImageSource: 'Url' | 'upload';
  ImageUrl?: string | null;
  ImageUpload?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones".
 */
export interface ShippingZone {
  id: string;
  cityName: string;
  cityNameAr: string;
  shippingPrice: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  user: string | User;
  orderNumber: string;
  items: {
    product: string | Product;
    title?: string | null;
    image?: string | null;
    quantity: number;
    price?: number | null;
    total?: number | null;
    selectedOptions?: string | null;
    optionType?: string | null;
    optionValue?: string | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  shipping: {
    zone: string | ShippingZone;
    city?: string | null;
    price?: number | null;
  };
  total?: number | null;
  status?: ('pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled') | null;
  payment: {
    method: 'cash' | 'stripe';
    status?: ('pending' | 'paid' | 'failed' | 'refunded' | 'cash_on_delivery') | null;
    stripePaymentIntentId?: string | null;
  };
  customer?: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  paidAt?: string | null;
  shippedAt?: string | null;
  deliveredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user: string | User;
  product: string | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-views".
 */
export interface ProductView {
  id: string;
  user: string | User;
  product: string | Product;
  views: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'countries';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'Subscripe';
        value: string | Subscripe;
      } | null)
    | ({
        relationTo: 'Notes';
        value: string | Note;
      } | null)
    | ({
        relationTo: 'shipping-zones';
        value: string | ShippingZone;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'product-views';
        value: string | ProductView;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phoneNumber?: T;
  gender?: T;
  pendingEmail?: T;
  pendingEmailToken?: T;
  pendingEmailTokenExpiresAt?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  des?: T;
  desAr?: T;
  slug?: T;
  slugAr?: T;
  showInHomePage?: T;
  ImageSource?: T;
  ImageUrl?: T;
  uploadImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  subtitle?: T;
  subtitleAr?: T;
  longDes?: T;
  longDesAr?: T;
  slug?: T;
  slugAr?: T;
  isNewest?: T;
  ShowInDiscountSection?: T;
  important?: T;
  isBestSeller?: T;
  category?: T;
  type?: T;
  typeAr?: T;
  choices?:
    | T
    | {
        choiceType?: T;
        choiceTypeAr?: T;
        options?:
          | T
          | {
              value?: T;
              valueAr?: T;
              availability?: T;
              priceAfter?: T;
              priceBefore?: T;
              ImageSource?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  reviewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  subtitle?: T;
  subtitleAr?: T;
  des?: T;
  desAr?: T;
  country?: T;
  rate?: T;
  ClientName?: T;
  isApproved?: T;
  product?: T;
  productOption?: T;
  image?:
    | T
    | {
        ImageSource?: T;
        image?: T;
        imageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Subscripe_select".
 */
export interface SubscripeSelect<T extends boolean = true> {
  Email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  slug?: T;
  slugAr?: T;
  des?: T;
  desAr?: T;
  longDes?: T;
  lonDesAr?: T;
  brandName?: T;
  brandNameAr?: T;
  isImportant?: T;
  ImageSource?: T;
  ImageUrl?: T;
  ImageUpload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones_select".
 */
export interface ShippingZonesSelect<T extends boolean = true> {
  cityName?: T;
  cityNameAr?: T;
  shippingPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  orderNumber?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        image?: T;
        quantity?: T;
        price?: T;
        total?: T;
        selectedOptions?: T;
        optionType?: T;
        optionValue?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?:
    | T
    | {
        zone?: T;
        city?: T;
        price?: T;
      };
  total?: T;
  status?: T;
  payment?:
    | T
    | {
        method?: T;
        status?: T;
        stripePaymentIntentId?: T;
      };
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        email?: T;
      };
  paidAt?: T;
  shippedAt?: T;
  deliveredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-views_select".
 */
export interface ProductViewsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  websiteName: string;
  websiteNameAr: string;
  HeaderVideo: string;
  TextOverVideo: {
    title: string;
    titleAr: string;
    hero: string;
    heroAr: string;
    subTitle: string;
    subTitleAr: string;
    id?: string | null;
  }[];
  Partner: {
    title: string;
    titleAr: string;
    subtitle: string;
    subtitleAr: string;
    Images?:
      | {
          ImageSource: 'Url' | 'upload';
          ImageUrl?: string | null;
          ImageUpload?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  SecondHeader: {
    SecondHeaderVideo: string;
    title: string;
    titleAr: string;
    subtitle: string;
    subtitleAr: string;
  };
  ReviewsSection: {
    title: string;
    titleAr: string;
    subtitle: string;
    subtitleAr: string;
    des: string;
    desAr: string;
    reviewTitle: string;
    reviewTitleAr: string;
    ImageSource: 'Url' | 'upload';
    ImageUrl?: string | null;
    ImageUpload?: (string | null) | Media;
  };
  discountSection: {
    discountTitle: string;
    discountTitleAr: string;
  };
  BestSellingSection: {
    title: string;
    titleAr: string;
    des: string;
    desAr: string;
    ImageSource: 'Url' | 'upload';
    ImageUrl?: string | null;
    ImageUpload?: (string | null) | Media;
  };
  BannerSection: {
    title: string;
    titleAr: string;
    spanTitle: string;
    spanTitleAr: string;
    des: string;
    desAr: string;
    ImageSource: 'Url' | 'upload';
    ImageUrl?: string | null;
    ImageUpload?: (string | null) | Media;
  };
  NotesSection: {
    title: string;
    titleAr: string;
    des: string;
    desAr: string;
    ImageSource: 'Url' | 'upload';
    ImageUrl?: string | null;
    ImageUpload?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: string;
  CategoriesPageData?: {
    title?: string | null;
    titleAr?: string | null;
    des?: string | null;
    desAr?: string | null;
  };
  allProducts: {
    title?: string | null;
    titleAr?: string | null;
    slug: string;
    slugAr: string;
    productsCount?: string | null;
    ImageSource: 'Url' | 'upload';
    ImageUrl?: string | null;
    ImageUpload?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  title: string;
  titleAr: string;
  subtitle: string;
  subtitleAr: string;
  HeaderOne: string;
  HeaderOneAr: string;
  DesOne: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  DesOneAR: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  DesTwo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  DesTwoAR: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  HeaderTwo: string;
  HeaderTwoAr: string;
  Articles?:
    | {
        title: string;
        titleAr: string;
        des: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        desAr: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        imageSource?: ('url' | 'upload') | null;
        image?: (string | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceTitle: string;
  serviceTitleAr: string;
  serviceSubtitle: string;
  serviceSubtitleAr: string;
  Services?:
    | {
        title: string;
        titleAr: string;
        des: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        desAr: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        imageSource?: ('url' | 'upload') | null;
        image?: (string | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  titleEn: string;
  titleAr: string;
  descriptionEn?: string | null;
  descriptionAr?: string | null;
  faqItems?:
    | {
        questionEn: string;
        questionAr: string;
        answerEn: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        answerAr: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-page".
 */
export interface ContactUsPage {
  id: string;
  title: string;
  titleAr: string;
  subtitle: string;
  subtitleAr: string;
  PhoneNumber: string;
  email: string;
  address: string;
  addressAr: string;
  /**
   * Paste full Google Maps iframe code (we will extract src automatically)
   */
  locationIframe: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  footer: {
    websiteName: string;
    websiteNameAr: string;
    title: string;
    titleAr: string;
    span: string;
    spanAr: string;
    des: string;
    desAr: string;
    faceBookLink?: string | null;
    instgramLink?: string | null;
    whatsappLink?: string | null;
    xLink?: string | null;
    leftImageSource: 'Url' | 'upload';
    leftImageUrl?: string | null;
    leftImageUpload?: (string | null) | Media;
    rightImageSource: 'Url' | 'upload';
    rightImageUrl?: string | null;
    rightImageUpload?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes-page".
 */
export interface NotesPage {
  id: string;
  titleEn: string;
  titleAr: string;
  descriptionEn?: string | null;
  descriptionAr?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy".
 */
export interface Policy {
  id: string;
  title: string;
  titleAr: string;
  description?: string | null;
  descriptionAr?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentAr: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-delivery".
 */
export interface ShippingDelivery {
  id: string;
  title: string;
  titleAr: string;
  description?: string | null;
  descriptionAr?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentAr: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions".
 */
export interface TermsAndCondition {
  id: string;
  title: string;
  titleAr: string;
  description?: string | null;
  descriptionAr?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentAr: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  websiteName?: T;
  websiteNameAr?: T;
  HeaderVideo?: T;
  TextOverVideo?:
    | T
    | {
        title?: T;
        titleAr?: T;
        hero?: T;
        heroAr?: T;
        subTitle?: T;
        subTitleAr?: T;
        id?: T;
      };
  Partner?:
    | T
    | {
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        Images?:
          | T
          | {
              ImageSource?: T;
              ImageUrl?: T;
              ImageUpload?: T;
              id?: T;
            };
      };
  SecondHeader?:
    | T
    | {
        SecondHeaderVideo?: T;
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
      };
  ReviewsSection?:
    | T
    | {
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        des?: T;
        desAr?: T;
        reviewTitle?: T;
        reviewTitleAr?: T;
        ImageSource?: T;
        ImageUrl?: T;
        ImageUpload?: T;
      };
  discountSection?:
    | T
    | {
        discountTitle?: T;
        discountTitleAr?: T;
      };
  BestSellingSection?:
    | T
    | {
        title?: T;
        titleAr?: T;
        des?: T;
        desAr?: T;
        ImageSource?: T;
        ImageUrl?: T;
        ImageUpload?: T;
      };
  BannerSection?:
    | T
    | {
        title?: T;
        titleAr?: T;
        spanTitle?: T;
        spanTitleAr?: T;
        des?: T;
        desAr?: T;
        ImageSource?: T;
        ImageUrl?: T;
        ImageUpload?: T;
      };
  NotesSection?:
    | T
    | {
        title?: T;
        titleAr?: T;
        des?: T;
        desAr?: T;
        ImageSource?: T;
        ImageUrl?: T;
        ImageUpload?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  CategoriesPageData?:
    | T
    | {
        title?: T;
        titleAr?: T;
        des?: T;
        desAr?: T;
      };
  allProducts?:
    | T
    | {
        title?: T;
        titleAr?: T;
        slug?: T;
        slugAr?: T;
        productsCount?: T;
        ImageSource?: T;
        ImageUrl?: T;
        ImageUpload?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  subtitle?: T;
  subtitleAr?: T;
  HeaderOne?: T;
  HeaderOneAr?: T;
  DesOne?: T;
  DesOneAR?: T;
  DesTwo?: T;
  DesTwoAR?: T;
  HeaderTwo?: T;
  HeaderTwoAr?: T;
  Articles?:
    | T
    | {
        title?: T;
        titleAr?: T;
        des?: T;
        desAr?: T;
        imageSource?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  serviceTitle?: T;
  serviceTitleAr?: T;
  serviceSubtitle?: T;
  serviceSubtitleAr?: T;
  Services?:
    | T
    | {
        title?: T;
        titleAr?: T;
        des?: T;
        desAr?: T;
        imageSource?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  titleEn?: T;
  titleAr?: T;
  descriptionEn?: T;
  descriptionAr?: T;
  faqItems?:
    | T
    | {
        questionEn?: T;
        questionAr?: T;
        answerEn?: T;
        answerAr?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-page_select".
 */
export interface ContactUsPageSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  subtitle?: T;
  subtitleAr?: T;
  PhoneNumber?: T;
  email?: T;
  address?: T;
  addressAr?: T;
  locationIframe?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footer?:
    | T
    | {
        websiteName?: T;
        websiteNameAr?: T;
        title?: T;
        titleAr?: T;
        span?: T;
        spanAr?: T;
        des?: T;
        desAr?: T;
        faceBookLink?: T;
        instgramLink?: T;
        whatsappLink?: T;
        xLink?: T;
        leftImageSource?: T;
        leftImageUrl?: T;
        leftImageUpload?: T;
        rightImageSource?: T;
        rightImageUrl?: T;
        rightImageUpload?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes-page_select".
 */
export interface NotesPageSelect<T extends boolean = true> {
  titleEn?: T;
  titleAr?: T;
  descriptionEn?: T;
  descriptionAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy_select".
 */
export interface PolicySelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-delivery_select".
 */
export interface ShippingDeliverySelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions_select".
 */
export interface TermsAndConditionsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  description?: T;
  descriptionAr?: T;
  content?: T;
  contentAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}